### ISSUE TITLE
PicoPal

### ISSUE THREAD

**Issue by superboy8900** [fcipaq/picohero_pplib#2]
Apparently someone took this name before. Here is something I found.  Portable Raspberry Pico Pal aim to monitor your sleep. [https://www.hackster.io/news/patrick-michell-s-sleep-keeper-and-portable-raspberry-pico-pal-aim-to-track-your-sleeping-habits-d40bf6d85164](https://www.hackster.io/news/patrick-michell-s-sleep-keeper-and-portable-raspberry-pico-pal-aim-to-track-your-sleeping-habits-d40bf6d85164) Nevermind, no copyright on it.

**Comment by fcipaq** [comment]
Man, that "pico" namespace seems to be crowded... Thanks for the hint. Let's see if I can come up with yet another name...

**Comment by superboy8900** [comment]
Yeah, I think everyone uses the raspberry pico.

**Comment by superboy8900** [comment]
How about **Pico Entertainment System**
