### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by superboy8900** [fcipaq/picohero_pplib#5]
Do we need a soldering iron, and where do you get the PCB from?

**Comment by fcipaq** [comment]
Hey,

yes you would need that although I am currently checking if I can get a PCB manufacturer to preassemble the most difficult components.
I like your enthusiasm but the Github issues are not the best choice for answering that kind of questions. I am considering opening a discord maybe. Until then, if you have a question, please just drop me a mail (you can find the address in the source code headers).

Also, I like your suggested name "Pico Entertainment System".

Best regards

**Comment by superboy8900** [comment]
I think I sent it. Is it a web.de email?
